### ISSUE TITLE
这个怎么处理啊，是不是NODE.js 版本不对

### ISSUE THREAD

**Issue by bulesky520** [htmlk/ts-tyt#1]
E:\OSChinaGit\jump\ts-tyt\app.js:43
  socket.on('distance', async function (data) {
                        ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393

**Comment by stevekeol** [comment]
已经确定是版本问题！V8.9.1及以上即可
